### PR TITLE
arm64: DT: Add device tree support for SoMC Kugo

### PR DESCRIPTION
**Pull request by oshmoun**
basic support for kugo :)
hw buttons work, touchscreen works, audio works but no incall audio, cameras work.
no display though, though it is only the panel, as screen mirroring through adb works.
and device only boots when attached to usb for some reason.
defconfig used to build https://del.dog/kusekeweti.ini

### CODE REVIEW

**Comment by bartcubbins** [comment]
@oshmoun thanks, I would be grateful for dmesg;).
when I get some free time I will take care about kugo

**Comment by oshmoun** [comment]
sure, here it is
https://del.dog/orobupogep.sh

**Comment by bartcubbins** [comment]
@oshmoun please switch to an old msmfb display hal and you get a working display

**Comment by oshmoun** [comment]
you are right, that did it :)
though I wonder why

**Comment by bartcubbins** [comment]
I'll try to figure it out asap

**Pull request merged**
