### PR TITLE
[7.8.r1] Merge CAF LA.UM.7.8.r1-06000-SDM710.0

### PR DESCRIPTION
**Pull request by konradybcio**
Update kernel to CAF tag LA.UM.7.8.r1-06000-SDM710.0

branch: kernel.lnx.4.9.r14-rel
tag: LA.UM.7.8.r1-06000-SDM710.0
commit: a383c707("diag: Prevent out-of-bound access while processing userspace data")
remote: https://source.codeaurora.org/quic/la/kernel/msm-4.9/

### CODE REVIEW

**Comment by bartcubbins** [comment]
@sjllls @suzu-treble if you're still working on loire devices please test this pr

**Comment by sjllls** [comment]
@bartcubbins I will test it after I finish my exams these days.

**Comment by sjllls** [comment]
@bartcubbins This PR works fine.

**Comment by bartcubbins** [comment]
@sjllls thanks;)

**Comment by bartcubbins** [comment]
I will update techpack part as soon as possible

**Pull request merged**
